# Certificates deployment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/certificates.namespace.yaml
- resources/cluster-issuer-selfsigned.cluster-issuer.cert-manager.yaml
- resources/wildcard.lourenco.local-tls.certificate.cert-manager.yaml
- resources/route53-lourenco.cluster-issuer.cert-manager.yaml
- resources/wildcard.lourenco.ch-tls.certificate.cert-manager.yaml
- secrets/route53-lourenco.yaml

patches:
- path: patches/wildcard.lourenco.local-tls.certificate.cert-manager.reflector.namespaces.yaml
  target:
    group: cert-manager.io
    version: v1
    kind: Certificate
    namespace: certificates
    name: wildcard.lourenco.local-tls
- path: patches/wildcard.lourenco.ch-tls.certificate.cert-manager.reflector.namespaces.yaml
  target:
    group: cert-manager.io
    version: v1
    kind: Certificate
    namespace: certificates
    name: wildcard.lourenco.ch-tls
