# Nextcloud server setup
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: server-nextcloud

resources:
- resources/data-server-nextcloud.persistentvolumeclaim.yaml
- resources/html-server-nextcloud.persistentvolumeclaim.yaml
- resources/server-nginx-nextcloud.ingressroute.traefik.yaml
- resources/server-nginx-nextcloud.service.clusterip.yaml
- resources/server-nginx-nextcloud.statefulset.yaml

replicas:
- name: server-nginx-nextcloud
  count: 1

images:
- name: nextcloud
  newTag: 26-fpm-alpine
- name: nginx
  newTag: 1.25.1-alpine
- name: xperimental/nextcloud-exporter
  newTag: 0.6.1

configMapGenerator:
- name: server-nginx-nextcloud
  envs:
  - configs/params.properties
  files:
  - configs/nginx.conf
  - configs/zz-docker.conf

secretGenerator:
- name: server-nextcloud
  files:
  - nextcloud-admin-password=secrets/nextcloud-admin.pwd
